name: Build ATC_Thermometer

on:
  pull_request:
    branches: [ master ]
    paths:
      - ATC_Thermometer/**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/skaldo/telink-sdk/telink-sdk:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ATC_Thermometer
        env:
          TEL_PATH: /opt/Telink_825X_SDK
        run: |
          cd ATC_Thermometer
          make
          cd $GITHUB_WORKSPACE
          ls -la
